### ISSUE TITLE
Parse response data to model does not work with an object

### ISSUE THREAD

**Issue by 5v3n-08** [codeBelt/sjs-base-model#24]
Hey :)

I would like to parse the following response into appropriate models:

```
message: "success"
token: "xxx"
authUser: {id: "1", status: 1, email: "xxx",…}
models: {
    App: [{id: "1", name: "x1"},{id: "2", name: "x2"}]
    Location: [{id: "1", name: "y1"},{id: "2", name: "y2"}]
    Project: [{id: "1", name: "z1"},{id: "2", name: "z2"}]
}
```

My response model looks like this:
```
export default class AuthenticationResponseModel extends BaseModel {
  public readonly message: string = '';
  public readonly token: string | undefined = undefined;
  public readonly authUser: AuthUserModel = AuthUserModel as any;
  public readonly models: {
    App: AppModel[];
  } = { App: [AppModel as any] };

...
```

But if I take for example "App" out of the object and move it into the "root - level" it works exactly the same as with the "AuthUserModel".

`public readonly App: AppModel[] = [AppModel as any];`

Is this feature not supported or is something wrong in my code? 

If this is not supported could you add this?

Thanks already for the help :)

**Comment by codeBelt** [comment]
You need to create a BaseModel for `models`. If a child property on a BaseModel is not another BaseModel then it does nothing with it.

```ts
export default class ModelsModel extends BaseModal {
  public readonly App: AppModel[] = [AppModel as any];
}
```

```ts
...
  public readonly authUser: AuthUserModel = AuthUserModel as any;
  public readonly models: ModelsModel = ModelsModel as any;
...
```

**Comment by 5v3n-08** [comment]
Great thanks! :)

**Comment by 5v3n-08** [comment]
One more question sry :D How can i extends models? For example I have a UserModel and the AuthUserModal should inherit everything from UserModel.

**Comment by codeBelt** [comment]
Check out this working example https://codesandbox.io/s/sjs-base-model-extend-68clb?file=/src/index.ts

Instead of `AuthUserModel` extending `BaseModel` you would extend `UserModel` which extends `BaseModel`. Also you need to pass the `data` to the `super` of the class you are extending.

```ts
export class UserModel extends BaseModel {
  readonly firstName: string = "";
  readonly lastName: string = "";
  readonly email: string = "";

  constructor(data: RecursivePartial<UserModel>) {
    super();

    this.update(data);
  }
}

export class AuthUserModel extends UserModel {
  readonly permissions: string[] = [];

  constructor(data: RecursivePartial<AuthUserModel>) {
    super(data);

    this.update(data);
  }
}

const json = {
  permissions: ["admin"],
  firstName: "Robert",
  lastName: "Cool",
  email: "example@example.com"
};

console.log(new AuthUserModel(json).toJSON());
```

**Comment by 5v3n-08** [comment]
Perfect thank you very much!
